# -*- coding: utf-8 -*-
"""py_pd_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FkSYXqiR7EURz7aCQqMHVzCSqPTdf3KU
"""

import pandas as pd
df1 = pd.DataFrame(# 괄호 아래로 보내면 오류남
     {
         'a' : [1, 2, 3],
         'b' : [4, 5, 6],
          'c' : [7, 8, 9]
      },
     index = ['aa','bb','cc']
      )

print(df1)

import pandas as pd
df2 = pd.DataFrame(# 괄호 아래로 보내면 오류남
     {'a' : [1, 2, 3, 0],
      'b' : [4, 5, 3, 6],
      'c' : [7, 8, 9, 0]},
      index = ['A','B','C','D']
      )

print(df2)

df3 = pd.DataFrame(
    {'a' : [1, 2, 3],
     'b' : [4, 5, 6],
     'c' : [7, 8, 9]},
 index = pd.MultiIndex.from_tuples(
     [('D','l'), ('D','m'), ('E','n')],
     names = ['d', 'e']
     )
 )

print(df3)

pd.melt(df1)

pd.concat([df1,df2])